services:
    ekinsport-backend:
        container_name: ekinsport-backend
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./:/app/
            - /app/node_modules
        environment:
            WAIT_HOSTS: mysql:3306
            NODE_ENV: development
            DD_ENV: development
            DD_SERVICE: ekinsport-api
            DD_VERSION: ${npm_package_version:-1.0.0}
        networks:
            - app-network
networks:
  app-network:
    driver: bridge